### ISSUE TITLE
Grateful for multi-select for mapping imported columns in KDX

### ISSUE THREAD

**Issue by kadreher** [kddart/kdxplore#13]
Greetings,

I've been importing csv files into KDX that have many columns of trial attributes. I had been clicking on them one-by-one on the right side to make them trial attributes and that was very time-consuming. But, then I realized today that I could select multiple rows on the left side and then classify ALL of them as trial attributes at once during the import into KDX. This made me so happy! Thanks so much for this helpful feature. I am just sad (and feel dumb) that I did not realize that it existed before.

Sincerely,
kate

**Comment by spelexander** [comment]
Glad it was helpful! 

This feature is now more emphasised in the documentation at:
http://www.kddart.org/help/kdxplore/
