### ISSUE TITLE
CSV issues causing premature ageing!

### ISSUE THREAD

**Issue by Hearni** [kddart/kdxplore#15]
Hi Guys,

A number of issues to report. 

When creating a scoring set using curated values an exported csv contains values of inactivated plots, a KDX behaves "properly" when imported to KDS and shows no traits at all for the deactivated entries (I did initially have a data integrity heart attack- you owe me half a head of grey hair). Alas when exporting a csv from KDS after importing the scoring set and adding more data the "inactivated" plots are now visible in the spreadsheet (see below). 

I can't import a KDS generated csv or a manually edited csv into KDX and add the data as another source to KDX- KDX complains that the trial exists and I can only import under a different trial name and then KDX sometimes thinks there is an issue with the trial planting data being invalid (I hadn't touched it) (even if I select the trial name box and edit to the database trial name it isn't having it). 

For a number of applications we need functional csv transfer and this was the "fallback" file format- HELP please!

S

![capture1](https://cloud.githubusercontent.com/assets/25251182/26803539/333d43aa-4a0a-11e7-87fb-00a74c9c6b37.PNG)
Kate has the same challenge

[food test2,test set csv,2017-06-05_161004.xlsx](https://github.com/kddart/kdxplore/files/1053211/food.test2.test.set.csv.2017-06-05_161004.xlsx)

[food test2,test set csv,2017-06-05_153728.zip](https://github.com/kddart/kdxplore/files/1053207/food.test2.test.set.csv.2017-06-05_153728.zip)

[food test2,baylake,2017-06-05_160403.xlsx](https://github.com/kddart/kdxplore/files/1053206/food.test2.baylake.2017-06-05_160403.xlsx)

![captureii](https://cloud.githubusercontent.com/assets/25251182/26803871/7e77c9a2-4a0b-11e7-9e98-f11fa3655074.PNG)

**Comment by spelexander** [comment]
Thank you for reporting these issues, we are seeing to them right away.

**Comment by spelexander** [comment]
These issues should now be fixed in the latest beta (1.1.2) and production (2.1.2) releases of KDXplore. Can I close this issue after you confirm?

**Comment by Hearni** [comment]
HI Alex,

Neither Kate or I have had time to look at this yet- we will. For now close the issues- we will post more if we find any.

Cheers,

S

P.S. would be good to skype with you at some point to make sure I have interpreted everything properly- next week ok for you?

Dr. Sarah J Hearne | Molecular Geneticist, SeeD- Maize lead.

International Maize and Wheat Improvement Center (CIMMYT)
Carretera México-Veracruz Km. 45, El Batán, Texcoco, México, C.P. 56237
tel: +52 (55) 5804 2004 ext 1374

website<http://www.cimmyt.org/en/> | twitter<https://twitter.com/cimmyt> | facebook<https://www.facebook.com/CIMMYT> | linkedin<https://www.linkedin.com/company/cimmyt> | flickr<https://www.flickr.com/photos/cimmyt/> | youtube<https://www.youtube.com/user/CIMMYTint>
[cid:image003.png@01D2EFE2.3C45CB20]
Maize and wheat science for improved livelihoods.

This e-mail may contain confidential and/or privileged information from CIMMYT and/or its collaborators. Unless explicitly allowed in writing by an authorized representative, any use, reproduction, storage, retransmission or unauthorized disclosure of such information, whether in part or in whole, is hereby forbidden. If you are not the intended recipient of this e-mail, please notify the sender and delete it immediately.
Este correo electrónico puede contener información confidencial y/o privilegiada de CIMMYT y/o sus colaboradores. Salvo que un representante autorizado lo faculte por escrito, se prohíbe el uso, reproducción, almacenamiento, retransmisión o divulgación no autorizada, parcial o total, de dicha información. Si usted no es el destinatario del presente correo, por favor, notifíquelo al remitente y bórrelo inmediatamente.
