### ISSUE TITLE
Unable to import .kdx file from KDX 2.0.45 into KDS 2.0.72 due to DB issue 

### ISSUE THREAD

**Issue by acra1907** [kddart/kdxplore#19]
Unable to import .kdx file from KDX 2.0.45 into KDS 2.0.72 due to DB issue, KDX exports file with DB version 27 and KDS gave some error related to DB version 29.

**Comment by acra1907** [comment]
I am attaching the file I exported from KDX 2.0.45 below: 

[1 SATYT - RGO,Maturity traits,2017-08-25_150417.zip](https://github.com/kddart/kdxplore/files/1253063/1.SATYT.-.RGO.Maturity.traits.2017-08-25_150417.zip)

**Comment by kadreher** [comment]
@acra1907 I want to try to add Sarah and Claudio to this issue but I don't know how

**Comment by spelexander** [comment]
This should be fixed in the latest push of source code.
You will also notice an additional choice in the scoring set export dialog, which allows for explicit
export for KDSmart 3 - DB 30.

I will wait for your confirmation to close the issue.
