### ISSUE TITLE
KDX 2.0.45 cannot add more instances of a trait to an existing trait

### ISSUE THREAD

**Issue by kadreher** [kddart/kdxplore#21]
Greetings,

We did a few tests and could not figure out how to add  additional instances to any traits that are already visible in the trial, i.e.. traits that were loaded during the initial trial import do not show up or offer the opportunity to modify the number of instances

![image](https://user-images.githubusercontent.com/8202843/29743393-a541d61e-8a56-11e7-8e97-265492785370.png)

Is this the intended behavior?

Saludos,
kate

**Comment by kadreher** [comment]
Hi Alex,

Can you please let me know why this ticket was closed? Was this fixed? Or was this the expected behavior?

Many thanks,
kate

**Comment by spelexander** [comment]
This should be fixed in the latest push of source code.

I will wait for your confirmation to close the issue.
