### ISSUE TITLE
Cannot import trait files with TraitType using the same file that is exported from kdx 2.0.46

### ISSUE THREAD

**Issue by kadreher** [kddart/kdxplore#24]
Greetings,

We wanted to upload a list of traits to KDX that would include both plot and sub-plot level traits. We tried to check the online documentation but we could not find information on how to submit this information in a csv file. Therefore, I thought that it would be logical to assume that the csv file exported from the traits tab in KDX would provide the format for importing traits into KDX. 

But, when we try to upload the attached file we were unsuccessful. Originally we tried to just use this format with new traits. That failed. Then I tried to export this file and then deleted these traits to see if I could recreate traits that we knew had been successfully created in KDX previously. But that also was not successful.
[traits_sub-plot.zip](https://github.com/kddart/kdxplore/files/1366571/traits_sub-plot.zip)

Here is the error message:
![image](https://user-images.githubusercontent.com/8202843/31313231-b0bb5f20-aba2-11e7-8b79-2a8c9f478189.png)

Can you please provide @Hearni, @acra1907 and me with a template that we can use to upload mixed lists of plot and sub-plot level traits?
 
Also, just curious . . . do you know why we cannot upload csv files to GitHub issues?

Thanks for your help with this - and apologies if we missed this in the documentation somewhere.

**Comment by manil007** [comment]
Hey Kate,
Thanks for reporting this issue.
I can see the confusion here , both KDXplore and KDSmart expect "Specimen" as the heading for 
Trait Level for subplot traits.

We are aiming towards keeping import definitions same in both KDX and KDS.
We are going to make the import section of online help same for both applications.

Next releases in both KDX and KDS will allow you to use "Sub-Plot" or "Specimen" or "Individual" 
to import the trait level.

was this the only issue with your import?
Please test KDS 3.0.3 for this issue next week.

**Comment by kadreher** [comment]
Hi Manil,

Thanks very much for your quick response.

I actually cannot remember if we tested loading this traits file in any version of KDS. If so, it was Carolina who tested it whom I tagged in this issue, so maybe she can write back on Monday about whether this also happened in KDS. But we definitely tested it in KDX 2.0.46. We were just trying to import the trait file itself.

As you can see from the file that I provided, the KDX software exports the word Sub-plot if you use the csv export from the Traits tab which is what lead us to believe that this was the proper terminology for this import file.

Did we have the correct column header?

Thanks again,
kate

**Comment by manil007** [comment]
Dear kate,
Thanks for replying on weekend.
Yes column header looks fine, just use "Specimen" instead of "Sub-Plot" with KDX 2.0.46.

I  understand that this is a confusion and the new releases of KDX and KDS will support 
for Plot Level:
"TrialUnit" , "Plot"

for Sub-Plot level:
"Sub-Plot", "Specimen","Plant","Individual".

i decided to add Plant too. just because some users might use it.
I will close this issue now.
a import TTT csv help will be added to our online help soon.
 
Thanks
Manil

**Comment by kadreher** [comment]
Thanks very much, Manil.

We’ll try to use specimen for KDX 2.0.46 and let you know if we experience any problems.

Sincerely,
kate
