### ISSUE TITLE
scoring set creation issues

### ISSUE THREAD

**Issue by Hearni** [kddart/kdxplore#5]
Select all/ select none does not work. You only have the option to "create" if you select all traits click by click. Even when you can create a Java error occurs- see attached.
[KDXplore_Error_20170321_103505.txt](https://github.com/kddart/kdxplore/files/858935/KDXplore_Error_20170321_103505.txt)

**Comment by spelexander** [comment]
As of KDXplore version 2.1.1 Production and 1.1.1 beta this issue has been fixed.
