### ISSUE TITLE
Specimens not created when I import a csv file with Specimen count

### ISSUE THREAD

**Issue by kadreher** [kddart/kdxplore#6]
Greetings,

I am trying to create specimens in bulk for a trial. I attempted to load the attached csv file in KDXplore 2.0.44. 
[Seed_health_template_with_composite_samples.zip](https://github.com/kddart/kdxplore/files/870254/Seed_health_template_with_composite_samples.zip)

You can see in the attached screenshot that I was able to create the trial, but, it says that 0 specimens were created.
[Cannot create specimens in KDX.docx](https://github.com/kddart/kdxplore/files/870253/Cannot.create.specimens.in.KDX.docx)

Can you please help me to understand what I am doing wrong? Or is KDX not supposed to support the creation of specimens using the SpecimenCount column?

Many thanks,
kate

**Comment by kadreher** [comment]
Please note that if I added specimens individually in KDS, took measurements, and then exported the data as a .kdx file, I could see the data in KDX and curate it. But, it is not ideal to add specimens individually in KDS.

**Comment by kadreher** [comment]
I tried again to import a csv file into KDX this time with specimen traits and also got an error. The traits are already loaded in KDX as specimen traits. 
[Seed_health_template_with_composite_samples_and_spec_traits.zip](https://github.com/kddart/kdxplore/files/870366/Seed_health_template_with_composite_samples_and_spec_traits.zip)

I got the error: At Line#2, Column#17 heading='MDMV_ELISA_Individual
Trait 'MDMV_ELISA_Individual' level=Sub-Plot invalid for Non-Specimen

**Comment by kadreher** [comment]
Greetings,

I hoped that maybe I would be able to create Specimens in the 2.1.1 production release but I just tried and was unsuccessful. 

![image](https://cloud.githubusercontent.com/assets/8202843/26758978/e90a0a8a-48b4-11e7-9d20-1869929797e5.png)

But then I saw this text:
Trial CSV import complete: KD2
Elapsed time: 0:00
10 Plots
Sample Measurement Counts: 10 Plot, 0 Specimen

And I see no indication that there are any specimens in this trial once I open it. I tried to check the online documentation, but, although the user guide refers to a section on "File Formats" I could not find that or any information about loading specimens to KDX or adding specimens to plots in KDX in 
http://www.kddart.org/help/kdxplore/KDXplore-TrialManagement.html#import-trials

Is it supposed to be possible to use the SpecimenCount column when importing to be able to create a defined number of specimens for each plot?

I am attaching my input file here for you to check in case I have formatted it incorrectly.

Thank you.
[kd2.zip](https://github.com/kddart/kdxplore/files/1050122/kd2.zip)

**Comment by spelexander** [comment]
This issue should no longer be present as of in 2.1.2, 1.1.2 and 1.0.46 versions of KDXplore.

Associated help documentation for CSV import formatting in relation to subplot data can be found here (Import is the same in both KDXplore and KDSmart):
http://www.kddart.org/help/kdsmart/kdsmart-app-b.html
